<?php
function deena_menu()
{
    $items = array();
    $items['deena_input'] = array(
        'title' => 'DNA Maker',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('deena_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['deena_result_page'] = array(
        'title' => 'DNA',
        'page callback' => 'make_dna',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function deena_form()
{
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => 'Enter the first half of the DNA string',
        '#element_validate' => array('validate_entry'),
        '#prefix' => '<i style="color:orange">Hint: only uppercase "A", "T", "C", or "G" will be accepted as valid input',
        '#suffix' => '</i>',
        '#required' => TRUE,
    );
    $from['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Get your DNA!' // exclamation marks never get old
    );
    return $form;
}

//validate user entry
function validate_entry($element){
    $phrase_to_parse = $element['#value'];
    if(preg_match("/[ACGT]/", $phrase_to_parse)){
        return true;
        //
    }else{
        return form_set_error("Valid DNA letters are 'A', 'C', 'G', or 'T' (capitalized, please)");
    }
}

function getDNAstring($input){
    $output = "";
    $phrase_to_reflect = str_split($input);
    foreach($phrase_to_reflect as $letter){
        if($letter == 'G'){
            $output .= 'C';
        }elseif ($letter == 'C') {
            $output .= 'G';
        }elseif ($letter == 'A') {
            $output .= 'T';
        }elseif($letter == 'T'){
            $output .= 'A';
        }else{
            echo "This should never print";
        }
    }
    return $input . ", " . $output;
}
